### ISSUE TITLE
Error fetching team members

### ISSUE THREAD

**Issue by palaparthi** [spirit3189/team-member-management#1]
After setting up the project, I hit 500 error going to http://localhost:5173. Can you fix this?

<img width="1497" alt="Screenshot 2024-11-05 at 9 48 56 PM" src="https://github.com/user-attachments/assets/3288d882-cda9-464e-9185-a45c450d6e2a">

**Comment by spirit3189** [comment]
The 500 Internal Server Error indicates that something is wrong with the Django backend.
Can you check what’s the response for http://127.0.0.1:8000/api/team-members/

**Comment by spirit3189** [comment]
I have updated the README file with clear instructions, including a step to load initial data.
`python manage.py loaddata team_members`

Here’s a quick summary of the steps to resolve this:

**Remove the existing database**
`rm backend/insta_team_management/db.sqlite3`

**Reapply migrations**
```
python manage.py makemigrations
python manage.py migrate
```
**Load Initial Data**:
`python manage.py loaddata team_members`

After completing the above steps, restart the development server:
`python manage.py runserver`
These steps ensure the database and initial data are properly configured.

Let me know if the issue persists, and I’ll be happy to assist further!

**Comment by palaparthi** [comment]
Below is the error, can you do a clean setup and make sure the project runs, thanks.

```
Internal Server Error: /api/team-members/
Traceback (most recent call last):
  File "/Users/sree/projects/iw-take-homes/team-member-management/backend/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/sree/projects/iw-take-homes/team-member-management/backend/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: api_teammember
```

**Comment by palaparthi** [comment]
Nvm, I had to run `python manage.py makemigrations api` specifically to create the migrations
